version: '3'

networks:
  carsales-network:
    external: false

services:

  db:
    image: postgres:15
    restart: always
    container_name: producao_dbhost
    environment:
      - POSTGRES_DB=producao_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"

    networks:
      - carsales-network