apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  carsales-app
  name: carsales-app-deployment
  #namespace: carsales-ns
spec:
  selector:
    matchLabels:
      app: carsales-app
  replicas: 3
  template:
    metadata:
      labels:
        app: carsales-app
    spec:
      containers:
        - image: mvsouza30/app-test:v1
          imagePullPolicy:  Always
          name: carsales-app
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_SERVER_APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: carsales-configmap
                  key: SPRING_DATASOURCE_SERVER_APP_PORT
            - name: SPRING_DATASOURCE_SERVER_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: carsales-configmap
                  key: SPRING_DATASOURCE_SERVER_PROTOCOL
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: carsales-configmap
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-password
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: carsales-configmap
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            - name: SPRING_DATASOURCE_DATABASE_PORTS
              valueFrom:
                configMapKeyRef:
                  name: carsales-configmap
                  key: SPRING_DATASOURCE_DATABASE_PORTS