apiVersion: v1
kind: Service
metadata:
  name: carsales-app-service
  namespace: carsales-ns
spec:
  type: ClusterIP
  selector:
    greeting: carsales-app
    version: one
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080