CREATE TABLE IF NOT EXISTS cars (
  id SERIAL PRIMARY KEY,
  marca VARCHAR(25) NOT NULL,
  modelo VARCHAR(25) NOT NULL,
  cor VARCHAR(10) NOT NULL,
  ano int NOT NULL,
  preco DECIMAL(10, 2) NOT NULL,
  descricao VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS pre_sales (
  id SERIAL PRIMARY KEY,
  cpf VARCHAR(15) NOT NULL,
  data VARCHAR(15) NOT NULL,
  marca VARCHAR(25) NOT NULL,
  modelo VARCHAR(25) NOT NULL,
  cor VARCHAR(10) NOT NULL,
  ano int NOT NULL,
  preco DECIMAL(10, 2) NOT NULL,
  descricao VARCHAR(255) NOT NULL,
  cod_vendas VARCHAR(25) NOT NULL,
  status VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS sold_cars (
  id SERIAL PRIMARY KEY,
  cpf VARCHAR(15) NOT NULL,
  data VARCHAR(15) NOT NULL,
  marca VARCHAR(25) NOT NULL,
  modelo VARCHAR(25) NOT NULL,
  cor VARCHAR(10) NOT NULL,
  ano int NOT NULL,
  preco DECIMAL(10, 2) NOT NULL,
  descricao VARCHAR(255) NOT NULL,
  cod_vendas VARCHAR(25) NOT NULL,
  status VARCHAR(15) NOT NULL
);