apiVersion: apps/v1
kind: Deployment
metadata:
  name: carsales-db-deployment
  namespace: carsales-ns
spec:
  selector:
    matchLabels:
      greeting: carsales-db
      version: two
  replicas: 3
  template:
    metadata:
      labels:
        greeting: carsales-db
        version: two
    spec:
      containers:
        - name: carsales-db
          image: "mvsouza30/db-prod:v1"
          env:
            - name: SPRING_DATASOURCE_DATABASE_PORTS
              valueFrom:
                configMapKeyRef:
                  name: carsales-configmap
                  key: SPRING_DATASOURCE_DATABASE_PORTS
            - name: SPRING_DATASOURCE_PORTS
              valueFrom:
                configMapKeyRef:
                  name: carsales-configmap
                  key: SPRING_DATASOURCE_PORTS
            - name: SPRING_DATASOURCE_TARGET_PORT
              valueFrom:
                configMapKeyRef:
                  name: carsales-configmap
                  key: SPRING_DATASOURCE_TARGET_PORT
            - name: SPRING_DATASOURCE_SERVER_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: carsales-configmap
                  key: SPRING_DATASOURCE_SERVER_PROTOCOL
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: carsales-configmap
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: carsales-configmap
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME