apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carsales-ingress
  namespace: carsales-ns
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - http:
        paths:
          - path: /swagger-ui/index.html
            pathType: ImplementationSpecific
            backend:
              service:
                name: carsales-app-service
                port:
                  number: 8080